//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WEBCAM.Context
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class WEBCAMEntities : DbContext
    {
        public WEBCAMEntities()
            : base("name=WEBCAMEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<C__MigrationHistory> C__MigrationHistory { get; set; }
        public virtual DbSet<AspNetRoles> AspNetRoles { get; set; }
        public virtual DbSet<AspNetUserClaims> AspNetUserClaims { get; set; }
        public virtual DbSet<AspNetUserLogins> AspNetUserLogins { get; set; }
        public virtual DbSet<AspNetUsers> AspNetUsers { get; set; }
        public virtual DbSet<Modulo> Modulo { get; set; }
        public virtual DbSet<Operaciones> Operaciones { get; set; }
        public virtual DbSet<RolOperacion> RolOperacion { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<TblCiudades> TblCiudades { get; set; }
        public virtual DbSet<TblDepartamentos> TblDepartamentos { get; set; }
        public virtual DbSet<TblDocumentosUsuarios> TblDocumentosUsuarios { get; set; }
        public virtual DbSet<TblGeneros> TblGeneros { get; set; }
        public virtual DbSet<TblPaises> TblPaises { get; set; }
        public virtual DbSet<TblTiposDocumentos> TblTiposDocumentos { get; set; }
    }
}
