//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WEBCAM.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblFotosUsuario
    {
        public System.Guid Id { get; set; }
        public string Nombre { get; set; }
        public string IdUsuario { get; set; }
        public int Estado { get; set; }
        public string Ruta { get; set; }
    
        public virtual AspNetUsers AspNetUsers { get; set; }
    }
}
